<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Werners-MacBook-Pro.local" name="Default test" tests="4" failures="1" timestamp="29 Mar 2015 19:00:58 GMT" time="0.54" errors="0">
  <testcase name="EventEvent" time="0.035" classname="bwi.prog2D.SS2015.wi14b128_Leitner.ExerciseSheet03.tests.EventTest"/>
  <testcase name="impact" time="0.037" classname="bwi.prog2D.SS2015.wi14b128_Leitner.ExerciseSheet03.tests.EventTest"/>
  <testcase name="testtoString" time="0.064" classname="bwi.prog2D.SS2015.wi14b128_Leitner.ExerciseSheet03.tests.EventTest"/>
  <testcase name="testtoString2" time="0.349" classname="bwi.prog2D.SS2015.wi14b128_Leitner.ExerciseSheet03.tests.EventTest">
    <failure type="java.lang.AssertionError" message="expected [cool artist @ my Venue on 09.03.2015
my fancy description
(250 attending (500))] but found [cool artist @ my Venue on 01.01.1970
my fancy description
(250 attending (500))]">
      <![CDATA[java.lang.AssertionError: expected [cool artist @ my Venue on 09.03.2015
my fancy description
(250 attending (500))] but found [cool artist @ my Venue on 01.01.1970
my fancy description
(250 attending (500))]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at bwi.prog2D.SS2015.wi14b128_Leitner.ExerciseSheet03.tests.EventTest.testtoString2(EventTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testtoString2 -->
</testsuite> <!-- Default test -->
